from __future__ import annotations

BOT_NAME = "LogicBot"
EXIT_COMMANDS = {"exit", "quit", "bye", "goodbye", "stop", "close", "end"}

DIRECT_INTENTS: dict[str, str] = {
    "hi": "greeting",
    "hello": "greeting",
    "hey": "greeting",
    "salam": "greeting",
    "assalam o alaikum": "greeting",
    "assalamu alaikum": "greeting",
    "good morning": "greeting",
    "good afternoon": "greeting",
    "good evening": "greeting",
    "thanks": "thanks",
    "thank you": "thanks",
    "shukriya": "thanks",
    "jazakallah": "thanks",
    "ok": "acknowledgement",
    "okay": "acknowledgement",
    "help": "help",
    "menu": "help",
    "commands": "help",
    "what can you do": "help",
    "who are you": "bot_identity",
    "what is your name": "bot_identity",
    "about you": "bot_identity",
    "what is ai": "ai_intro",
    "define ai": "ai_intro",
    "artificial intelligence": "ai_intro",
    "what is a chatbot": "chatbot_intro",
    "what is chatbot": "chatbot_intro",
    "what is rule based ai": "rule_based_ai",
    "what is rule based chatbot": "rule_based_ai",
    "what is project 1": "project_overview",
    "tell me about project 1": "project_overview",
    "project 1": "project_overview",
    "what is decodelabs": "decodelabs_intro",
    "decode labs": "decodelabs_intro",
    "decodelabs": "decodelabs_intro",
    "what is the internship": "internship_intro",
    "what is ai internship": "internship_intro",
    "what is the goal": "project_goal",
    "project goal": "project_goal",
    "what are the requirements": "requirements",
    "requirements": "requirements",
    "what skills will i learn": "skills",
    "skills": "skills",
    "what is sanitization": "sanitization",
    "what is input sanitization": "sanitization",
    "what is fallback": "fallback_design",
    "what is dictionary lookup": "dictionary_lookup",
    "what is ipo model": "ipo_model",
    "what is white box ai": "white_box",
    "what are ai guardrails": "guardrails",
    "why use if else": "if_else",
    "why use dictionary": "dictionary_reason",
    "how to submit": "submission_tips",
    "submission tips": "submission_tips",
    "how to get recommendation": "recommendation_tips",
    "contact decodelabs": "decodelabs_contact",
    "decodelabs contact": "decodelabs_contact",
    "is certificate free": "certificate_fee",
    "certificate fee": "certificate_fee",
    "is internship free": "internship_fee",
    "is it paid": "internship_fee",
    "what is my name": "ask_user_name",
    "do you know my name": "ask_user_name",
    "tell my name": "ask_user_name",
    "clear my name": "clear_user_name",
    "forget my name": "clear_user_name",
    "trace": "trace",
    "why this answer": "trace",
    "stats": "stats",
}

KEYWORD_INTENTS: dict[str, tuple[str, ...]] = {
    "greeting": ("hello", "hey", "hi", "salam", "good morning", "good evening", "good afternoon"),
    "bot_identity": ("your name", "who are you", "about yourself", "bot name", "logicbot"),
    "ai_intro": ("artificial intelligence", "ai means", "define ai", "meaning of ai"),
    "chatbot_intro": ("chatbot", "chat bot", "virtual assistant", "digital assistant"),
    "rule_based_ai": ("rule based", "predefined response", "hard coded", "fixed rule"),
    "project_overview": ("project 1", "first project", "rule based ai chatbot", "ai project"),
    "project_goal": ("goal", "objective", "aim", "purpose of project"),
    "requirements": ("requirement", "required", "must include", "criteria", "qualification", "badge"),
    "skills": ("skills", "learn", "concept", "control flow", "decision making", "logic building"),
    "decodelabs_intro": ("decode labs", "decodelabs", "training kit", "industrial training"),
    "internship_intro": ("internship", "intern", "artificial intelligence engineer", "foundation phase"),
    "certificate_fee": ("certificate fee", "pay for certificate", "certificate free", "certificate paid"),
    "internship_fee": ("internship free", "paid internship", "registration fee", "enrollment fee", "onboarding fee"),
    "decodelabs_contact": ("contact", "email", "phone", "website", "official details"),
    "sanitization": ("sanitize", "sanitization", "clean input", "lowercase", "whitespace", "punctuation"),
    "if_else": ("if else", "ifelse", "elif", "condition", "control flow"),
    "dictionary_lookup": ("dictionary lookup", "hash map", "direct lookup", "key value", "get method"),
    "dictionary_reason": ("why dictionary", "why hashmap", "faster than if", "efficient lookup"),
    "fallback_design": ("fallback", "unknown input", "not understand", "default response"),
    "ipo_model": ("ipo", "input process output", "input output", "process model"),
    "white_box": ("white box", "traceable", "transparent", "no mystery", "explainable"),
    "guardrails": ("guardrail", "safety", "filter", "blocking", "redaction"),
    "submission_tips": ("submit", "submission", "screenshots", "github", "zip", "report"),
    "recommendation_tips": ("recommendation", "stand out", "impress", "best work", "quality work"),
    "time_date": ("time", "date", "today"),
    "thanks": ("thank", "thanks", "shukriya", "jazak"),
    "goodbye": ("bye", "goodbye", "take care", "see you"),
}

RESPONSES: dict[str, list[str]] = {
    "greeting": [
        "Hello! I’m LogicBot. I can help you understand AI Project 1, DecodeLabs questions, and rule-based chatbot concepts.",
        "Hi, welcome back. Ask me about Project 1, AI basics, chatbot logic, or DecodeLabs details from the training kit.",
        "Assalam o Alaikum! I’m ready. Type 'help' if you want a quick menu of useful questions.",
    ],
    "goodbye": [
        "Goodbye! Keep your code clean, your logic clear, and your submission professional.",
        "Session ended safely. Best of luck with your DecodeLabs AI internship project!",
        "Take care! You built a strong foundation with rule-based AI.",
    ],
    "thanks": [
        "You’re welcome. Keep improving it step by step; that’s how a project starts looking professional.",
        "Anytime. A clean project with clear output always leaves a better impression.",
        "Glad to help. Ask another question whenever you want.",
    ],
    "acknowledgement": [
        "Great. What would you like to ask next?",
        "Okay, I’m listening.",
        "Perfect. You can ask about the project, requirements, code logic, or DecodeLabs.",
    ],
    "help": [
        "Try these: 'what is Project 1', 'requirements', 'what is sanitization', 'why use dictionary', 'what is DecodeLabs', 'certificate fee', 'submission tips', or 'exit'.",
        "I can answer AI basics, chatbot design, DecodeLabs Project 1 details, submission guidance, and internship-related questions from this project kit.",
    ],
    "bot_identity": [
        "I’m LogicBot, a rule-based assistant created for DecodeLabs AI Project 1. I don’t guess randomly; I follow clear rules.",
        "My name is LogicBot. I use sanitized input, if-else checks, dictionary matching, and fallback replies.",
    ],
    "ai_intro": [
        "Artificial Intelligence means building systems that can perform tasks normally linked with human thinking, like answering, reasoning, planning, or recognizing patterns.",
        "AI is not only deep learning. It starts with logic, rules, decisions, and problem solving. This project focuses on that foundation.",
    ],
    "chatbot_intro": [
        "A chatbot is a program that talks with users through text or voice. This project uses text input and predefined rule-based responses.",
        "A chatbot takes user input, processes it, and returns a useful response. That is the Input → Process → Output idea.",
    ],
    "rule_based_ai": [
        "Rule-based AI works with fixed instructions. If the user says something known, the bot matches a rule and gives a prepared answer.",
        "A rule-based chatbot is predictable and explainable because every answer comes from a written rule, not a hidden model.",
    ],
    "project_overview": [
        "Project 1 is a Rule-Based AI Chatbot. It is a foundation task where the bot responds to predefined inputs using control flow and logic.",
        "This project proves that you can build a continuous chatbot loop, sanitize input, match intents, handle unknown questions, and exit cleanly.",
    ],
    "project_goal": [
        "The goal is to create a simple chatbot that responds to predefined user inputs in a continuous conversation loop.",
        "The main objective is to show clear decision-making: receive input, clean it, match a rule, respond, and keep the chat running until exit.",
    ],
    "requirements": [
        "The core requirements are: handle greetings, handle exit commands, use if-else logic, and run in a continuous loop.",
        "For a stronger submission, I also include sanitization, 5+ intents, fallback replies, session memory, logging, tests, and documentation.",
    ],
    "skills": [
        "This project practices control flow, decision-making logic, dictionaries, input sanitization, response design, testing, and clean project structure.",
        "You learn the basic engineering mindset behind AI: predictable logic first, then smarter systems later.",
    ],
    "decodelabs_intro": [
        "DecodeLabs is shown in this training kit as the organization powering the Batch 2026 Artificial Intelligence Project 1 industrial training task.",
        "In this project, DecodeLabs gives interns a foundation task: build a rule-based AI chatbot before moving toward more advanced AI work.",
    ],
    "internship_intro": [
        "This AI internship task places you in the role of an Artificial Intelligence Engineer and starts with a foundation project based on control flow and logic.",
        "The internship project is not deep learning yet. It begins with explicit rules so the developer understands how controlled AI behavior works.",
    ],
    "certificate_fee": [
        "I should not guess about certificate payment. This project kit does not clearly say whether the certificate has a separate fee, so the safest step is to confirm through DecodeLabs’ official contact.",
        "Certificate fee details are not part of my verified project rules. Please verify with DecodeLabs directly before paying anything.",
    ],
    "internship_fee": [
        "I do not have enough verified fee information inside this project kit. For payment, registration, or certificate charges, always confirm with the official DecodeLabs email or website.",
        "Fee-related details can change, so I will not make a claim here. The best answer is to verify from DecodeLabs directly.",
    ],
    "decodelabs_contact": [
        "The training kit lists DecodeLabs contact details as: website www.decodelabs.tech, email decodelabs.tech@gmail.com, and phone +91 89330 06408.",
        "Official contact from the kit: www.decodelabs.tech and decodelabs.tech@gmail.com. Use official channels for fee or certificate confirmation.",
    ],
    "sanitization": [
        "Sanitization means cleaning user input before matching it. Example: '  HELLO!!! ' becomes 'hello', so the bot can understand it easily.",
        "Input sanitization improves matching by handling lowercase, extra spaces, and punctuation before the bot checks rules.",
    ],
    "if_else": [
        "If-else logic lets the bot make decisions step by step: if input is empty, ask again; else if it is exit, stop; else match an intent.",
        "If-else rules make the chatbot transparent because anyone can read the code and see why a response was selected.",
    ],
    "dictionary_lookup": [
        "Dictionary lookup stores phrases as keys and intents as values. It is cleaner than writing a very long if-elif ladder.",
        "A dictionary works like a small knowledge base: the user input is the key, and the bot finds the matching intent quickly.",
    ],
    "dictionary_reason": [
        "A dictionary keeps the project easier to maintain. You can add new questions in one place without rewriting the full chatbot logic.",
        "Dictionaries are useful because exact lookup is fast and the code stays cleaner than a long chain of repeated conditions.",
    ],
    "fallback_design": [
        "Fallback is the answer shown when no rule matches. It keeps the bot polite and useful instead of failing silently.",
        "A good fallback tells the user what the bot can answer and invites them to try a supported question.",
    ],
    "ipo_model": [
        "IPO means Input, Process, Output. The chatbot receives user text, processes it through rules, and prints a reply.",
        "The IPO model is a simple way to explain this chatbot: input is the message, process is rule matching, and output is the response.",
    ],
    "white_box": [
        "White-box AI means the logic is visible and traceable. In this chatbot, every reply can be explained by a direct rule or keyword match.",
        "This bot is white-box because there is no hidden model. The path from input to output is easy to inspect.",
    ],
    "guardrails": [
        "AI guardrails are rules that control what a system allows, blocks, or filters. Rule-based logic is often used as a safety layer.",
        "Guardrails make AI safer by applying deterministic checks before or after a flexible AI model responds.",
    ],
    "submission_tips": [
        "For submission, include the ZIP file, screenshots of the running bot, sample questions, README, project report, and test result screenshot.",
        "A strong submission should show clean code, useful responses, project structure, and proof that greetings, exit commands, fallback, and loop are working.",
    ],
    "recommendation_tips": [
        "To stand out, show more than the minimum: many intents, clean README, test cases, sample output, and a short report explaining your logic.",
        "For a better recommendation, write human-readable code, avoid messy comments, include screenshots, and explain how every requirement is completed.",
    ],
    "name_saved": [
        "Nice to meet you, {name}. I’ll remember your name during this session.",
        "Got it, {name}. I saved your name for this chat session.",
        "Great, {name}. Now you can ask me: what is my name?",
    ],
    "user_name": [
        "Your name is {name}. I stored it with a simple session variable.",
        "You told me your name is {name}, and I still remember it in this session.",
    ],
    "no_name": [
        "I don’t know your name yet. You can say: my name is Muneeb.",
        "You have not shared your name in this session. Try: call me Muneeb.",
    ],
    "name_cleared": [
        "Done. I cleared your name from this session.",
        "Your session name has been removed.",
    ],
    "trace_empty": [
        "No previous intent is available yet. Ask me a question first, then type 'trace'.",
    ],
    "fallback": [
        "I don’t have a rule for that yet. Try asking about Project 1, DecodeLabs, AI basics, requirements, or type 'help'.",
        "That question is outside my current knowledge base. A developer can add it as a new rule in intents.py.",
        "I could not match that input. Try: 'what is Project 1', 'requirements', 'certificate fee', or 'submission tips'.",
    ],
}
